/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObraObraIdRouteImport } from './routes/obra/$obraId'
import { Route as ApiObrasRouteImport } from './routes/api/obras'
import { Route as ApiObrasObraIdRouteImport } from './routes/api/obras/$obraId'
import { Route as ApiMetadataSearchRouteImport } from './routes/api/metadata/search'
import { Route as ApiMetadataDetailsRouteImport } from './routes/api/metadata/details'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as InternalAlfredNotificationsPullRouteImport } from './routes/internal/alfred/notifications/pull'
import { Route as InternalAlfredNotificationsAckRouteImport } from './routes/internal/alfred/notifications/ack'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraObraIdRoute = ObraObraIdRouteImport.update({
  id: '/obra/$obraId',
  path: '/obra/$obraId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObrasRoute = ApiObrasRouteImport.update({
  id: '/api/obras',
  path: '/api/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObrasObraIdRoute = ApiObrasObraIdRouteImport.update({
  id: '/$obraId',
  path: '/$obraId',
  getParentRoute: () => ApiObrasRoute,
} as any)
const ApiMetadataSearchRoute = ApiMetadataSearchRouteImport.update({
  id: '/api/metadata/search',
  path: '/api/metadata/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetadataDetailsRoute = ApiMetadataDetailsRouteImport.update({
  id: '/api/metadata/details',
  path: '/api/metadata/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalAlfredNotificationsPullRoute =
  InternalAlfredNotificationsPullRouteImport.update({
    id: '/internal/alfred/notifications/pull',
    path: '/internal/alfred/notifications/pull',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalAlfredNotificationsAckRoute =
  InternalAlfredNotificationsAckRouteImport.update({
    id: '/internal/alfred/notifications/ack',
    path: '/internal/alfred/notifications/ack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/login': typeof LoginRoute
  '/api/obras': typeof ApiObrasRouteWithChildren
  '/obra/$obraId': typeof ObraObraIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/metadata/details': typeof ApiMetadataDetailsRoute
  '/api/metadata/search': typeof ApiMetadataSearchRoute
  '/api/obras/$obraId': typeof ApiObrasObraIdRoute
  '/internal/alfred/notifications/ack': typeof InternalAlfredNotificationsAckRoute
  '/internal/alfred/notifications/pull': typeof InternalAlfredNotificationsPullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/login': typeof LoginRoute
  '/api/obras': typeof ApiObrasRouteWithChildren
  '/obra/$obraId': typeof ObraObraIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/metadata/details': typeof ApiMetadataDetailsRoute
  '/api/metadata/search': typeof ApiMetadataSearchRoute
  '/api/obras/$obraId': typeof ApiObrasObraIdRoute
  '/internal/alfred/notifications/ack': typeof InternalAlfredNotificationsAckRoute
  '/internal/alfred/notifications/pull': typeof InternalAlfredNotificationsPullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/login': typeof LoginRoute
  '/api/obras': typeof ApiObrasRouteWithChildren
  '/obra/$obraId': typeof ObraObraIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/metadata/details': typeof ApiMetadataDetailsRoute
  '/api/metadata/search': typeof ApiMetadataSearchRoute
  '/api/obras/$obraId': typeof ApiObrasObraIdRoute
  '/internal/alfred/notifications/ack': typeof InternalAlfredNotificationsAckRoute
  '/internal/alfred/notifications/pull': typeof InternalAlfredNotificationsPullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/login'
    | '/api/obras'
    | '/obra/$obraId'
    | '/api/auth/$'
    | '/api/metadata/details'
    | '/api/metadata/search'
    | '/api/obras/$obraId'
    | '/internal/alfred/notifications/ack'
    | '/internal/alfred/notifications/pull'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/login'
    | '/api/obras'
    | '/obra/$obraId'
    | '/api/auth/$'
    | '/api/metadata/details'
    | '/api/metadata/search'
    | '/api/obras/$obraId'
    | '/internal/alfred/notifications/ack'
    | '/internal/alfred/notifications/pull'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/login'
    | '/api/obras'
    | '/obra/$obraId'
    | '/api/auth/$'
    | '/api/metadata/details'
    | '/api/metadata/search'
    | '/api/obras/$obraId'
    | '/internal/alfred/notifications/ack'
    | '/internal/alfred/notifications/pull'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  LoginRoute: typeof LoginRoute
  ApiObrasRoute: typeof ApiObrasRouteWithChildren
  ObraObraIdRoute: typeof ObraObraIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMetadataDetailsRoute: typeof ApiMetadataDetailsRoute
  ApiMetadataSearchRoute: typeof ApiMetadataSearchRoute
  InternalAlfredNotificationsAckRoute: typeof InternalAlfredNotificationsAckRoute
  InternalAlfredNotificationsPullRoute: typeof InternalAlfredNotificationsPullRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$obraId': {
      id: '/obra/$obraId'
      path: '/obra/$obraId'
      fullPath: '/obra/$obraId'
      preLoaderRoute: typeof ObraObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/obras': {
      id: '/api/obras'
      path: '/api/obras'
      fullPath: '/api/obras'
      preLoaderRoute: typeof ApiObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/obras/$obraId': {
      id: '/api/obras/$obraId'
      path: '/$obraId'
      fullPath: '/api/obras/$obraId'
      preLoaderRoute: typeof ApiObrasObraIdRouteImport
      parentRoute: typeof ApiObrasRoute
    }
    '/api/metadata/search': {
      id: '/api/metadata/search'
      path: '/api/metadata/search'
      fullPath: '/api/metadata/search'
      preLoaderRoute: typeof ApiMetadataSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metadata/details': {
      id: '/api/metadata/details'
      path: '/api/metadata/details'
      fullPath: '/api/metadata/details'
      preLoaderRoute: typeof ApiMetadataDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/alfred/notifications/pull': {
      id: '/internal/alfred/notifications/pull'
      path: '/internal/alfred/notifications/pull'
      fullPath: '/internal/alfred/notifications/pull'
      preLoaderRoute: typeof InternalAlfredNotificationsPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/alfred/notifications/ack': {
      id: '/internal/alfred/notifications/ack'
      path: '/internal/alfred/notifications/ack'
      fullPath: '/internal/alfred/notifications/ack'
      preLoaderRoute: typeof InternalAlfredNotificationsAckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiObrasRouteChildren {
  ApiObrasObraIdRoute: typeof ApiObrasObraIdRoute
}

const ApiObrasRouteChildren: ApiObrasRouteChildren = {
  ApiObrasObraIdRoute: ApiObrasObraIdRoute,
}

const ApiObrasRouteWithChildren = ApiObrasRoute._addFileChildren(
  ApiObrasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  LoginRoute: LoginRoute,
  ApiObrasRoute: ApiObrasRouteWithChildren,
  ObraObraIdRoute: ObraObraIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMetadataDetailsRoute: ApiMetadataDetailsRoute,
  ApiMetadataSearchRoute: ApiMetadataSearchRoute,
  InternalAlfredNotificationsAckRoute: InternalAlfredNotificationsAckRoute,
  InternalAlfredNotificationsPullRoute: InternalAlfredNotificationsPullRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
