/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariantCRouteImport } from './routes/variant-c'
import { Route as VariantBRouteImport } from './routes/variant-b'
import { Route as VariantARouteImport } from './routes/variant-a'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObraObraIdRouteImport } from './routes/obra/$obraId'
import { Route as ApiMetadataSearchRouteImport } from './routes/api/metadata/search'
import { Route as ApiMetadataImageRouteImport } from './routes/api/metadata/image'
import { Route as ApiMetadataDetailsRouteImport } from './routes/api/metadata/details'
import { Route as InternalAlfredNotificationsPullRouteImport } from './routes/internal/alfred/notifications/pull'
import { Route as InternalAlfredNotificationsMarkReadRouteImport } from './routes/internal/alfred/notifications/mark-read'
import { Route as InternalAlfredNotificationsAckRouteImport } from './routes/internal/alfred/notifications/ack'

const VariantCRoute = VariantCRouteImport.update({
  id: '/variant-c',
  path: '/variant-c',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantBRoute = VariantBRouteImport.update({
  id: '/variant-b',
  path: '/variant-b',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantARoute = VariantARouteImport.update({
  id: '/variant-a',
  path: '/variant-a',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraObraIdRoute = ObraObraIdRouteImport.update({
  id: '/obra/$obraId',
  path: '/obra/$obraId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetadataSearchRoute = ApiMetadataSearchRouteImport.update({
  id: '/api/metadata/search',
  path: '/api/metadata/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetadataImageRoute = ApiMetadataImageRouteImport.update({
  id: '/api/metadata/image',
  path: '/api/metadata/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetadataDetailsRoute = ApiMetadataDetailsRouteImport.update({
  id: '/api/metadata/details',
  path: '/api/metadata/details',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalAlfredNotificationsPullRoute =
  InternalAlfredNotificationsPullRouteImport.update({
    id: '/internal/alfred/notifications/pull',
    path: '/internal/alfred/notifications/pull',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalAlfredNotificationsMarkReadRoute =
  InternalAlfredNotificationsMarkReadRouteImport.update({
    id: '/internal/alfred/notifications/mark-read',
    path: '/internal/alfred/notifications/mark-read',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalAlfredNotificationsAckRoute =
  InternalAlfredNotificationsAckRouteImport.update({
    id: '/internal/alfred/notifications/ack',
    path: '/internal/alfred/notifications/ack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/variant-a': typeof VariantARoute
  '/variant-b': typeof VariantBRoute
  '/variant-c': typeof VariantCRoute
  '/obra/$obraId': typeof ObraObraIdRoute
  '/api/metadata/details': typeof ApiMetadataDetailsRoute
  '/api/metadata/image': typeof ApiMetadataImageRoute
  '/api/metadata/search': typeof ApiMetadataSearchRoute
  '/internal/alfred/notifications/ack': typeof InternalAlfredNotificationsAckRoute
  '/internal/alfred/notifications/mark-read': typeof InternalAlfredNotificationsMarkReadRoute
  '/internal/alfred/notifications/pull': typeof InternalAlfredNotificationsPullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/variant-a': typeof VariantARoute
  '/variant-b': typeof VariantBRoute
  '/variant-c': typeof VariantCRoute
  '/obra/$obraId': typeof ObraObraIdRoute
  '/api/metadata/details': typeof ApiMetadataDetailsRoute
  '/api/metadata/image': typeof ApiMetadataImageRoute
  '/api/metadata/search': typeof ApiMetadataSearchRoute
  '/internal/alfred/notifications/ack': typeof InternalAlfredNotificationsAckRoute
  '/internal/alfred/notifications/mark-read': typeof InternalAlfredNotificationsMarkReadRoute
  '/internal/alfred/notifications/pull': typeof InternalAlfredNotificationsPullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/variant-a': typeof VariantARoute
  '/variant-b': typeof VariantBRoute
  '/variant-c': typeof VariantCRoute
  '/obra/$obraId': typeof ObraObraIdRoute
  '/api/metadata/details': typeof ApiMetadataDetailsRoute
  '/api/metadata/image': typeof ApiMetadataImageRoute
  '/api/metadata/search': typeof ApiMetadataSearchRoute
  '/internal/alfred/notifications/ack': typeof InternalAlfredNotificationsAckRoute
  '/internal/alfred/notifications/mark-read': typeof InternalAlfredNotificationsMarkReadRoute
  '/internal/alfred/notifications/pull': typeof InternalAlfredNotificationsPullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/explorar'
    | '/login'
    | '/variant-a'
    | '/variant-b'
    | '/variant-c'
    | '/obra/$obraId'
    | '/api/metadata/details'
    | '/api/metadata/image'
    | '/api/metadata/search'
    | '/internal/alfred/notifications/ack'
    | '/internal/alfred/notifications/mark-read'
    | '/internal/alfred/notifications/pull'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/explorar'
    | '/login'
    | '/variant-a'
    | '/variant-b'
    | '/variant-c'
    | '/obra/$obraId'
    | '/api/metadata/details'
    | '/api/metadata/image'
    | '/api/metadata/search'
    | '/internal/alfred/notifications/ack'
    | '/internal/alfred/notifications/mark-read'
    | '/internal/alfred/notifications/pull'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/explorar'
    | '/login'
    | '/variant-a'
    | '/variant-b'
    | '/variant-c'
    | '/obra/$obraId'
    | '/api/metadata/details'
    | '/api/metadata/image'
    | '/api/metadata/search'
    | '/internal/alfred/notifications/ack'
    | '/internal/alfred/notifications/mark-read'
    | '/internal/alfred/notifications/pull'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  VariantARoute: typeof VariantARoute
  VariantBRoute: typeof VariantBRoute
  VariantCRoute: typeof VariantCRoute
  ObraObraIdRoute: typeof ObraObraIdRoute
  ApiMetadataDetailsRoute: typeof ApiMetadataDetailsRoute
  ApiMetadataImageRoute: typeof ApiMetadataImageRoute
  ApiMetadataSearchRoute: typeof ApiMetadataSearchRoute
  InternalAlfredNotificationsAckRoute: typeof InternalAlfredNotificationsAckRoute
  InternalAlfredNotificationsMarkReadRoute: typeof InternalAlfredNotificationsMarkReadRoute
  InternalAlfredNotificationsPullRoute: typeof InternalAlfredNotificationsPullRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variant-c': {
      id: '/variant-c'
      path: '/variant-c'
      fullPath: '/variant-c'
      preLoaderRoute: typeof VariantCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variant-b': {
      id: '/variant-b'
      path: '/variant-b'
      fullPath: '/variant-b'
      preLoaderRoute: typeof VariantBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variant-a': {
      id: '/variant-a'
      path: '/variant-a'
      fullPath: '/variant-a'
      preLoaderRoute: typeof VariantARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$obraId': {
      id: '/obra/$obraId'
      path: '/obra/$obraId'
      fullPath: '/obra/$obraId'
      preLoaderRoute: typeof ObraObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metadata/search': {
      id: '/api/metadata/search'
      path: '/api/metadata/search'
      fullPath: '/api/metadata/search'
      preLoaderRoute: typeof ApiMetadataSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metadata/image': {
      id: '/api/metadata/image'
      path: '/api/metadata/image'
      fullPath: '/api/metadata/image'
      preLoaderRoute: typeof ApiMetadataImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metadata/details': {
      id: '/api/metadata/details'
      path: '/api/metadata/details'
      fullPath: '/api/metadata/details'
      preLoaderRoute: typeof ApiMetadataDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/alfred/notifications/pull': {
      id: '/internal/alfred/notifications/pull'
      path: '/internal/alfred/notifications/pull'
      fullPath: '/internal/alfred/notifications/pull'
      preLoaderRoute: typeof InternalAlfredNotificationsPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/alfred/notifications/mark-read': {
      id: '/internal/alfred/notifications/mark-read'
      path: '/internal/alfred/notifications/mark-read'
      fullPath: '/internal/alfred/notifications/mark-read'
      preLoaderRoute: typeof InternalAlfredNotificationsMarkReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/alfred/notifications/ack': {
      id: '/internal/alfred/notifications/ack'
      path: '/internal/alfred/notifications/ack'
      fullPath: '/internal/alfred/notifications/ack'
      preLoaderRoute: typeof InternalAlfredNotificationsAckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  VariantARoute: VariantARoute,
  VariantBRoute: VariantBRoute,
  VariantCRoute: VariantCRoute,
  ObraObraIdRoute: ObraObraIdRoute,
  ApiMetadataDetailsRoute: ApiMetadataDetailsRoute,
  ApiMetadataImageRoute: ApiMetadataImageRoute,
  ApiMetadataSearchRoute: ApiMetadataSearchRoute,
  InternalAlfredNotificationsAckRoute: InternalAlfredNotificationsAckRoute,
  InternalAlfredNotificationsMarkReadRoute:
    InternalAlfredNotificationsMarkReadRoute,
  InternalAlfredNotificationsPullRoute: InternalAlfredNotificationsPullRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
